import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({ src: "./fonts/FrutigerLTArabic55Roman.ttf" });

export const metadata: Metadata = {
  title: "Almosafer Code Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} max-w-[1100px] mx-auto`}>
        {children}
      </body>
    </html>
  );
}
